version: '3.7'

services:
  auth:
    container_name: billman-auth
    command: npm run start:dev
    env_file:
      - ./auth/.env
    environment:
      - MONGO_URI=mongodb://billman-auth-mongo/billman-auth
      - GOOGLE_OAUTH_REDIRECT_URI=http://localhost:3000/callback
      - FACEBOOK_OAUTH_REDIRECT_URI=http://localhost:3000/callback
    build:
      context: ./auth
    user: 'node:node'
    volumes:
      - './auth:/home/node/app:rw'
    depends_on:
      - billman-auth-mongo
    networks:
      - mongo_net
      - gateway_net

  billman-auth-mongo:
    image: mongo:4.4.4-bionic
    container_name: billman-auth-mongo
    logging:
      driver: none
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net

  web:
    container_name: billman-web
    command: npm run start:dev
    env_file:
      - ./web/.env
    environment:
      - SNOWPACK_PUBLIC_AUTH_URL=http://localhost:4000/auth
      - SNOWPACK_PUBLIC_APP_URL=http://localhost:3100
    build:
      context: ./web
    ports:
      - '3000:80'
    user: 'node:node'

  app:
    container_name: billman-app
    command: npm run start:dev
    env_file:
      - ./app/.env
    build:
      context: ./app
    ports:
      - '3100:80'
    user: 'node:node'

  gateway:
    container_name: billman-gateway
    env_file:
      - ./gateway/.env
    build:
      context: ./gateway
    ports:
      - '4000:80'
    user: 'node:node'
    volumes:
      - './gateway:/home/node/app:rw'
    networks:
      - gateway_net

volumes:
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge
  gateway_net:
    driver: bridge
