version: '3'
services:
  auth:
    container_name: billman-auth
    command: npm run start:dev
    env_file:
      - ./auth/.env
    environment:
      - MONGO_URI=mongodb://billman-auth-mongo/billman-auth
      - GOOGLE_OAUTH_REDIRECT_URI=http://localhost:8080/callback
      - FACEBOOK_OAUTH_REDIRECT_URI=http://localhost:8080/callback
    build:
      context: ./auth
    ports:
      - '3000:3000'
    user: 'node:node'
    volumes:
      - './auth:/home/node/app:rw'
    depends_on:
      - billman-auth-mongo
    networks:
      - mongo_net

  billman-auth-mongo:
    image: mongo:4.4.4-bionic
    container_name: billman-auth-mongo
    logging:
      driver: none
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net

  web:
    container_name: billman-web
    command: npm run start:dev
    env_file:
      - ./web/.env
    environment:
      - SNOWPACK_PUBLIC_AUTH_URL=http://localhost:3000
      - SNOWPACK_PUBLIC_APP_URL=http://localhost:8080
    build:
      context: ./web
    ports:
      - '8080:8080'
    user: 'node:node'
    depends_on:
      - auth

volumes:
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge
