http:
  port: 80

apiEndpoints:
  auth:
    paths: ['/auth', '/auth/*']
  expenses:
    paths: ['/expenses', '/expenses/*']

serviceEndpoints:
  auth:
    url: 'http://auth'
  expenses:
    url: 'http://expenses'

policies:
  - jwt
  - log
  - proxy

pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - log:
          action:
            message: ${req.method} ${req.originalUrl}
      - proxy:
          action:
            serviceEndpoint: auth
            stripPath: true

  expenses:
    apiEndpoints:
      - expenses
    policies:
      - log:
          action:
            message: ${req.method} ${req.originalUrl}
      - proxy:
          action:
            serviceEndpoint: expenses
            stripPath: true
