http:
  port: 80

apiEndpoints:
  auth:
    paths: ['/auth', '/auth/*']
  wallets:
    paths: ['/wallets', '/wallets/*']

serviceEndpoints:
  auth:
    url: 'http://auth'
  wallets:
    url: 'http://wallets'

policies:
  - jwt
  - log
  - proxy

pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - log:
          action:
            message: ${req.method} ${req.originalUrl}
      - proxy:
          action:
            serviceEndpoint: auth
            stripPath: true

  wallets:
    apiEndpoints:
      - wallets
    policies:
      - log:
          action:
            message: ${req.method} ${req.originalUrl}
      - proxy:
          action:
            serviceEndpoint: wallets
            stripPath: true
